[2025-01-11 13:31:37,460: INFO: main: Welcome to our custom log]
[2025-01-11 17:57:42,060: INFO: main: Welcome to our custom log]
[2025-01-11 18:05:01,336: INFO: main: Welcome to our custom log]
[2025-01-14 19:41:22,665: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 19:41:22,693: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 19:41:22,696: INFO: common: created directory at: artifacts_root]
[2025-01-14 19:41:22,696: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:00:33,013: ERROR: 3638245915: An error occurred during data ingestion: DataIngestionConfig.__init__() missing 2 required positional arguments: 'root_dir' and 'unzip_dir']
[2025-01-14 20:06:13,346: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:06:13,354: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:06:13,361: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:06:13,365: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:08:19,014: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:08:19,018: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:08:19,023: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:08:19,026: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:09:28,198: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:09:28,202: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:09:28,206: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:09:28,208: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:10:35,763: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:10:35,768: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:10:35,769: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:10:35,769: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:12:19,402: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:12:19,406: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:12:19,407: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:12:19,407: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:19:48,543: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:19:48,547: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:19:48,552: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:19:48,556: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:20:19,110: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:20:19,114: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:20:19,117: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:20:19,121: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:27:20,875: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:27:20,879: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:27:20,888: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:27:20,892: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:27:20,896: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-14 20:27:47,592: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:27:47,596: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:27:47,599: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:27:47,602: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:27:47,605: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-14 20:30:09,068: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-14 21:22:37,718: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-14 21:22:37,734: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 21:22:37,734: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 21:22:37,734: INFO: common: created directory at: artifacts_root]
[2025-01-14 21:22:37,738: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 21:22:37,739: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-14 21:25:13,962: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-14 21:25:14,835: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-17 20:02:20,207: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-17 20:02:20,208: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-17 20:02:20,218: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-17 20:02:20,220: INFO: common: created directory at: artifacts_root]
[2025-01-17 20:02:20,221: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-17 20:02:20,223: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-17 20:06:19,813: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-17 20:06:21,049: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-18 22:29:21,865: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 22:29:21,876: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 22:29:21,884: INFO: common: created directory at: artifacts_root]
[2025-01-18 22:29:21,884: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-01-18 22:42:30,263: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 22:42:30,270: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 22:42:30,272: INFO: common: created directory at: artifacts_root]
[2025-01-18 22:42:30,276: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-01-18 22:42:30,933: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-01-18 22:42:31,312: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-01-18 23:09:54,304: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-18 23:09:54,312: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 23:09:54,322: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 23:09:54,326: INFO: common: created directory at: artifacts_root]
[2025-01-18 23:09:54,342: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-18 23:09:54,346: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-18 23:15:34,799: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-18 23:15:36,413: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-18 23:15:36,413: INFO: main: *******************]
[2025-01-18 23:15:36,413: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-01-18 23:15:36,413: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 23:15:36,433: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 23:15:36,433: INFO: common: created directory at: artifacts_root]
[2025-01-18 23:15:36,437: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-01-18 23:15:36,438: ERROR: main: 'DataIngestion' object has no attribute 'get_base_model']
Traceback (most recent call last):
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\main.py", line 25, in <module>
    obj.main()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model.get_base_model()
AttributeError: 'DataIngestion' object has no attribute 'get_base_model'
[2025-01-18 23:28:41,152: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-18 23:28:41,167: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 23:28:41,167: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 23:28:41,167: INFO: common: created directory at: artifacts_root]
[2025-01-18 23:28:41,172: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-18 23:28:41,174: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-18 23:34:19,500: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-18 23:34:20,894: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-18 23:34:20,910: INFO: main: *******************]
[2025-01-18 23:34:20,910: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-01-18 23:34:20,910: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 23:34:20,918: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 23:34:20,919: INFO: common: created directory at: artifacts_root]
[2025-01-18 23:34:20,920: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-01-18 23:34:22,911: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-01-18 23:34:23,237: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-01-18 23:34:23,443: INFO: main: Prepare Base Model completed]
